export { default as StartScreen } from "./StartScreen";
export { default as LoginScreen } from "./LoginScreen";
export { default as RegisterScreen } from "./RegisterScreen";
export { default as ResetPasswordScreen } from "./ResetPasswordScreen";
export { default as HomeScreen } from "./HomeScreen";
export { default as QuizScreen } from "./QuizScreen";
export { default as EducationalScreen } from "./EducationalScreen"; 
export { default as LeaderboardScreen } from "./LeaderboardScreen";
export { default as SettingsScreen } from "./SettingsScreen";   
export { default as UserProfile} from "./UserProfile";