// This screen was generated by GitHub Copilot 

import React from "react";
import { View, Text, StyleSheet, TouchableOpacity } from "react-native";
import { useNavigation } from "@react-navigation/native";
import {MaterialIcons} from "@expo/vector-icons";
import { theme } from "../core/theme";

export default function SettingsScreen() {
  const navigation = useNavigation();

  return (
    <View style={styles.container}>
      <Text style={styles.header}>Settings</Text>
      
      {/* Notifications */}
      <TouchableOpacity style={styles.option}>
        <MaterialIcons name="notifications" size={24} color="#4399E6" />
        <Text style={styles.optionText}>Notifications</Text>
      </TouchableOpacity>

      {/* Privacy Settings */}
      <TouchableOpacity style={styles.option}>
        <MaterialIcons name="lock" size={24} color="#4399E6" />
        <Text style={styles.optionText}>Privacy</Text>
      </TouchableOpacity>

      {/*Support */}
      <TouchableOpacity style={styles.option}>
        <MaterialIcons name="help" size={24} color="#4399E6" />
        <Text style={styles.optionText}>Support</Text>
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.surface,
    padding: 20,
  },
  header: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 30,
    marginBottom: 20,
   
  },
  option: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  optionText: {
    fontSize: 16,
    marginLeft: 10,
  },
});
